# Generated by Django 4.2.3 on 2023-07-30 10:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_settings', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='b_', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('draft', 'Draft')], default='published', max_length=10)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cat', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category/icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/image')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='category/banner')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('draft', 'Draft')], default='published', max_length=10)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='NonDeleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='p_', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tax', models.IntegerField(blank=True, default=5, null=True)),
                ('unit', models.CharField(choices=[('liter', 'liter'), ('bunch', 'bunch'), ('dozen', 'dozen'), ('gm', 'gm'), ('kg', 'kg'), ('pkt', 'pkt'), ('box', 'box'), ('piece', 'piece')], max_length=100)),
                ('pack_size', models.DecimalField(decimal_places=3, max_digits=5)),
                ('min_qty', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], default='physical', max_length=10)),
                ('barcode', models.CharField(default=None, max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='products')),
                ('hover_image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_type', models.CharField(choices=[('percent', 'Percent'), ('flat', 'Flat')], default='percent', max_length=10)),
                ('qty', models.CharField(max_length=10)),
                ('sku', models.CharField(default=None, max_length=30, unique=True)),
                ('offer', models.CharField(blank=True, choices=[('buy1get1', 'Buy 1 Get 1'), ('today_deal', "Today's Deal"), ('Savings', 'Great Saving')], default=None, max_length=10, null=True)),
                ('cod', models.BooleanField(default=True, verbose_name='Cash on Delivery')),
                ('featured', models.BooleanField(default=False)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='products/meta')),
                ('status', models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('draft', 'Draft')], default='in_review', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='products.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='products.category')),
                ('currency', models.ForeignKey(default='Taka', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency', to='web_settings.currency')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('facebook', 'Facebook'), ('dailymotion', 'Dailymotion')], max_length=100, null=True)),
                ('link', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Video',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='product-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
            },
        ),
    ]
