# Generated by Django 4.2.3 on 2023-08-01 04:20

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_brand_image_alter_brand_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, choices=[('today_deal', "Today's Deal"), ('buy1get1', 'Buy 1 Get 1'), ('Savings', 'Great Saving')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('published', 'Published'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'piece'), ('box', 'box'), ('liter', 'liter'), ('dozen', 'dozen'), ('bunch', 'bunch'), ('gm', 'gm'), ('kg', 'kg'), ('pkt', 'pkt')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='provider',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('facebook', 'Facebook'), ('dailymotion', 'Dailymotion')], max_length=100, null=True),
        ),
    ]
