# Generated by Django 4.2.3 on 2023-08-01 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_vendor_alter_brand_slug_alter_brand_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('in_review', 'In Review')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('in_review', 'In Review')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, choices=[('today_deal', "Today's Deal"), ('Savings', 'Great Saving'), ('buy1get1', 'Buy 1 Get 1')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('in_review', 'In Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('liter', 'liter'), ('gm', 'gm'), ('bunch', 'bunch'), ('piece', 'piece'), ('dozen', 'dozen'), ('box', 'box'), ('pkt', 'pkt'), ('kg', 'kg')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='provider',
            field=models.CharField(blank=True, choices=[('vimeo', 'Vimeo'), ('youtube', 'YouTube'), ('dailymotion', 'Dailymotion'), ('facebook', 'Facebook')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Reviews',
            },
        ),
    ]
