# Generated by Django 4.2.3 on 2023-08-01 07:00

import autoslug.fields
from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_brand_status_alter_category_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='l_', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='title', unique=True)),
                ('image', models.ImageField(blank=True, default='location.jpg', null=True, upload_to='location')),
                ('address', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(choices=[('rejected', 'Rejected'), ('in_review', 'In Review'), ('disabled', 'Disabled'), ('published', 'Published'), ('draft', 'Draft')], default='published', max_length=10)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_review', 'In Review'), ('disabled', 'Disabled'), ('published', 'Published'), ('draft', 'Draft')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_review', 'In Review'), ('disabled', 'Disabled'), ('published', 'Published'), ('draft', 'Draft')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_review', 'In Review'), ('disabled', 'Disabled'), ('published', 'Published'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], default='physical', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('liter', 'liter'), ('dozen', 'dozen'), ('kg', 'kg'), ('piece', 'piece'), ('pkt', 'pkt'), ('box', 'box'), ('gm', 'gm'), ('bunch', 'bunch')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (2, '★★☆☆☆'), (5, '★★★★★')], default=None),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='provider',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('dailymotion', 'Dailymotion')], max_length=100, null=True),
        ),
    ]
