# Generated by Django 4.2.3 on 2023-08-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_location_tags_alter_brand_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='products.location'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published'), ('in_review', 'In Review')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published'), ('in_review', 'In Review')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published'), ('in_review', 'In Review')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, choices=[('Savings', 'Great Saving'), ('today_deal', "Today's Deal"), ('buy1get1', 'Buy 1 Get 1')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published'), ('in_review', 'In Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('flat', 'Flat')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'piece'), ('kg', 'kg'), ('liter', 'liter'), ('bunch', 'bunch'), ('dozen', 'dozen'), ('box', 'box'), ('pkt', 'pkt'), ('gm', 'gm')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(4, '★★★★☆'), (1, '★☆☆☆☆'), (5, '★★★★★'), (2, '★★☆☆☆'), (3, '★★★☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='provider',
            field=models.CharField(blank=True, choices=[('dailymotion', 'Dailymotion'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('facebook', 'Facebook')], max_length=100, null=True),
        ),
    ]
